apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nyat8u6u7-go
  janus-idp.io/tekton: nyat8u6u7-go
  backstage.io/kubernetes-id: nyat8u6u7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nyat8u6u7-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
