apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nyat8u6u7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyat8u6u7-go 
  name: nyat8u6u7-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nyat8u6u7-go
    weight: 100 
