apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nyat8u6u7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyat8u6u7-go 
  name: nyat8u6u7-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nyat8u6u7-go 
